name: Deploy

on:
  workflow_dispatch: {}
  #push:
  #  branches:
  #    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cd sns-manager && npm ci && npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: sns-manager/dist/
